### ISSUE TITLE
YouTube 브랜치에 있는 write.dart와 home.dart 사이 inputText 값 전달문제

### ISSUE THREAD

**Issue by millejuice** [Club-PARD/Tell-Me#1]
textfield사용하기 위해 textEditingController _editCon사용 _editCon.addListener()로 변화 있으면 감지
build안에 gestureDetector 이용해서 textfield안에 값 입력되면 그 값 inputText에 저장해서(여기까지 잘됨)
Home.dart 파일에서 id라는 값으로 받아오려고 하는데 이게 안되는거 같아요. 이거만 되면 url 값 파싱하는 패키지만 추가하면 
끝인데 여기서 막혀서 진행이 안되고 있어요 도.와.주.세.요
youtube브랜치 lib파일에 있습니다~

**Comment by millejuice** [comment]
53번 줄에 있는 url값은 사용자가 입력한 url에서 재생하는데 필요한 값 parse한 값이에요. 이거 elevatedButton 밖에서도 사용하려고 13번 줄에 class만들고 했는데 61번줄 argument로 전달을 못하네요...이거부터 해결해야 할것 같아요

**Comment by millejuice** [comment]
최근거 해결 값 넘기는거 할게요

**Comment by csc7545** [comment]
혹시 코드 푸쉬한 브랜치가 어디일까요?

**Comment by millejuice** [comment]
youtube입니당

**Comment by csc7545** [comment]
**Commit 내역 :**
  [FIX] home.dart 
  LateInitializationError: Field 'youtubeId' has not been initialized. 해결

**문제 :**
  late 키워드를 사용하면 해당 변수가 나중에 초기화될 것임을 나타냄 ㅇㅇ. 
  근데 youtubeId는 YoutubePlayerController가 초기화될 때 필요함. 
  
  문제는 YoutubePlayerController는 클래스가 생성될 때 초기화되고, youtubeId는 initState() 함수에서 초기화되기 때문임. 
  그래서 YoutubePlayerController가 초기화되는 시점에는
  youtubeId가 아직 초기화되지 않았기 때문에 LateInitializationError가 발생하는 거임. (아까 말한거)

**해결안 :** 
  YoutubePlayerController를 initState()에서 초기화


https://github.com/Club-PARD/Tell-Me/assets/74640695/b7a9e1b8-41f9-40c3-9ea7-9c16a822cde0
